version: '3'
services:
  api:
    image: nbh123/authflowservice
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    volumes:
      - /var/lib/docker/volumes/testdb/_data
      #- ./data:/data/db #windows
    networks:
      - backend
    ports:
      - "27017:27017"

  web-cli:
    image: nbh123/authflowservice
    links:
      - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
